import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/Providers/Provider";
import { CounterStoreProvider } from "@/Providers/CounterStoreProvider";
import ClientProvider from "@/Providers/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <CounterStoreProvider>
            <Provider>{children}</Provider>
          </CounterStoreProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
